package com.cxxy.eta8.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSCooperate<M extends BaseSCooperate<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCooperateName(java.lang.String CooperateName) {
		set("CooperateName", CooperateName);
		return (M)this;
	}
	
	public java.lang.String getCooperateName() {
		return getStr("CooperateName");
	}

}
