package com.cxxy.eta8.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAward<M extends BaseAward<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setAwardName(java.lang.String awardName) {
		set("awardName", awardName);
		return (M)this;
	}
	
	public java.lang.String getAwardName() {
		return getStr("awardName");
	}

	public M setAwardTypeId(java.lang.Integer awardTypeId) {
		set("awardTypeId", awardTypeId);
		return (M)this;
	}
	
	public java.lang.Integer getAwardTypeId() {
		return getInt("awardTypeId");
	}

	public M setCreateAt(java.util.Date createAt) {
		set("createAt", createAt);
		return (M)this;
	}
	
	public java.util.Date getCreateAt() {
		return get("createAt");
	}

	public M setUpdateAt(java.util.Date updateAt) {
		set("updateAt", updateAt);
		return (M)this;
	}
	
	public java.util.Date getUpdateAt() {
		return get("updateAt");
	}

}
