package com.cxxy.eta8.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCollege<M extends BaseCollege<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCollegeName(java.lang.String collegeName) {
		set("collegeName", collegeName);
		return (M)this;
	}
	
	public java.lang.String getCollegeName() {
		return getStr("collegeName");
	}

}
