package com.cxxy.eta8.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSubjectLinkTeacher<M extends BaseSubjectLinkTeacher<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSubjectId(java.lang.Integer SubjectId) {
		set("SubjectId", SubjectId);
		return (M)this;
	}
	
	public java.lang.Integer getSubjectId() {
		return getInt("SubjectId");
	}

	public M setUserId(java.lang.Integer UserId) {
		set("UserId", UserId);
		return (M)this;
	}
	
	public java.lang.Integer getUserId() {
		return getInt("UserId");
	}

	public M setCandidateId(java.lang.Integer CandidateId) {
		set("CandidateId", CandidateId);
		return (M)this;
	}
	
	public java.lang.Integer getCandidateId() {
		return getInt("CandidateId");
	}

}
