package com.cxxy.eta8.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSubjectSponsored<M extends BaseSubjectSponsored<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSubjectId(java.lang.Integer SubjectId) {
		set("SubjectId", SubjectId);
		return (M)this;
	}
	
	public java.lang.Integer getSubjectId() {
		return getInt("SubjectId");
	}

	public M setResearchId(java.lang.Integer ResearchId) {
		set("ResearchId", ResearchId);
		return (M)this;
	}
	
	public java.lang.Integer getResearchId() {
		return getInt("ResearchId");
	}

	public M setIsSecrecy(java.lang.Integer isSecrecy) {
		set("isSecrecy", isSecrecy);
		return (M)this;
	}
	
	public java.lang.Integer getIsSecrecy() {
		return getInt("isSecrecy");
	}

	public M setIsVoucher(java.lang.Integer isVoucher) {
		set("isVoucher", isVoucher);
		return (M)this;
	}
	
	public java.lang.Integer getIsVoucher() {
		return getInt("isVoucher");
	}

	public M setIsSubmitFill(java.lang.Integer isSubmitFill) {
		set("isSubmitFill", isSubmitFill);
		return (M)this;
	}
	
	public java.lang.Integer getIsSubmitFill() {
		return getInt("isSubmitFill");
	}

	public M setIsPromote(java.lang.Integer isPromote) {
		set("isPromote", isPromote);
		return (M)this;
	}
	
	public java.lang.Integer getIsPromote() {
		return getInt("isPromote");
	}

	public M setIsDutyFree(java.lang.Integer isDutyFree) {
		set("isDutyFree", isDutyFree);
		return (M)this;
	}
	
	public java.lang.Integer getIsDutyFree() {
		return getInt("isDutyFree");
	}

	public M setDutyFreeId(java.lang.Integer DutyFreeId) {
		set("DutyFreeId", DutyFreeId);
		return (M)this;
	}
	
	public java.lang.Integer getDutyFreeId() {
		return getInt("DutyFreeId");
	}

	public M setBelongId(java.lang.Integer BelongId) {
		set("BelongId", BelongId);
		return (M)this;
	}
	
	public java.lang.Integer getBelongId() {
		return getInt("BelongId");
	}

	public M setTypeId(java.lang.Integer TypeId) {
		set("TypeId", TypeId);
		return (M)this;
	}
	
	public java.lang.Integer getTypeId() {
		return getInt("TypeId");
	}

	public M setEntrustPlaceId(java.lang.Integer EntrustPlaceId) {
		set("EntrustPlaceId", EntrustPlaceId);
		return (M)this;
	}
	
	public java.lang.Integer getEntrustPlaceId() {
		return getInt("EntrustPlaceId");
	}

	public M setTopicId(java.lang.Integer TopicId) {
		set("TopicId", TopicId);
		return (M)this;
	}
	
	public java.lang.Integer getTopicId() {
		return getInt("TopicId");
	}

	public M setMainProjectName(java.lang.String MainProjectName) {
		set("MainProjectName", MainProjectName);
		return (M)this;
	}
	
	public java.lang.String getMainProjectName() {
		return getStr("MainProjectName");
	}

	public M setApplicationCode(java.lang.String ApplicationCode) {
		set("ApplicationCode", ApplicationCode);
		return (M)this;
	}
	
	public java.lang.String getApplicationCode() {
		return getStr("ApplicationCode");
	}

	public M setIntroduction(java.lang.String Introduction) {
		set("Introduction", Introduction);
		return (M)this;
	}
	
	public java.lang.String getIntroduction() {
		return getStr("Introduction");
	}

	public M setRemarks(java.lang.String Remarks) {
		set("Remarks", Remarks);
		return (M)this;
	}
	
	public java.lang.String getRemarks() {
		return getStr("Remarks");
	}

	public M setCooperateId(java.lang.Integer CooperateId) {
		set("CooperateId", CooperateId);
		return (M)this;
	}
	
	public java.lang.Integer getCooperateId() {
		return getInt("CooperateId");
	}

	public M setContractNum(java.lang.String ContractNum) {
		set("ContractNum", ContractNum);
		return (M)this;
	}
	
	public java.lang.String getContractNum() {
		return getStr("ContractNum");
	}

	public M setFundNum(java.lang.String FundNum) {
		set("FundNum", FundNum);
		return (M)this;
	}
	
	public java.lang.String getFundNum() {
		return getStr("FundNum");
	}

	public M setContractName(java.lang.String ContractName) {
		set("ContractName", ContractName);
		return (M)this;
	}
	
	public java.lang.String getContractName() {
		return getStr("ContractName");
	}

	public M setContractId(java.lang.Integer ContractId) {
		set("ContractId", ContractId);
		return (M)this;
	}
	
	public java.lang.Integer getContractId() {
		return getInt("ContractId");
	}

	public M setContractFund(java.lang.String ContractFund) {
		set("ContractFund", ContractFund);
		return (M)this;
	}
	
	public java.lang.String getContractFund() {
		return getStr("ContractFund");
	}

	public M setCooperatePrincipal(java.lang.String CooperatePrincipal) {
		set("CooperatePrincipal", CooperatePrincipal);
		return (M)this;
	}
	
	public java.lang.String getCooperatePrincipal() {
		return getStr("CooperatePrincipal");
	}

	public M setBankName(java.lang.String BankName) {
		set("BankName", BankName);
		return (M)this;
	}
	
	public java.lang.String getBankName() {
		return getStr("BankName");
	}

	public M setBankAccount(java.lang.String BankAccount) {
		set("BankAccount", BankAccount);
		return (M)this;
	}
	
	public java.lang.String getBankAccount() {
		return getStr("BankAccount");
	}

	public M setContractDuty(java.lang.String ContractDuty) {
		set("ContractDuty", ContractDuty);
		return (M)this;
	}
	
	public java.lang.String getContractDuty() {
		return getStr("ContractDuty");
	}

	public M setPayId(java.lang.Integer PayId) {
		set("PayId", PayId);
		return (M)this;
	}
	
	public java.lang.Integer getPayId() {
		return getInt("PayId");
	}

	public M setEconomicId(java.lang.Integer EconomicId) {
		set("EconomicId", EconomicId);
		return (M)this;
	}
	
	public java.lang.Integer getEconomicId() {
		return getInt("EconomicId");
	}

	public M setSocietyId(java.lang.Integer SocietyId) {
		set("SocietyId", SocietyId);
		return (M)this;
	}
	
	public java.lang.Integer getSocietyId() {
		return getInt("SocietyId");
	}

	public M setSourceId(java.lang.Integer SourceId) {
		set("SourceId", SourceId);
		return (M)this;
	}
	
	public java.lang.Integer getSourceId() {
		return getInt("SourceId");
	}

	public M setTechnicalId(java.lang.Integer TechnicalId) {
		set("TechnicalId", TechnicalId);
		return (M)this;
	}
	
	public java.lang.Integer getTechnicalId() {
		return getInt("TechnicalId");
	}

	public M setPropertyId(java.lang.Integer PropertyId) {
		set("PropertyId", PropertyId);
		return (M)this;
	}
	
	public java.lang.Integer getPropertyId() {
		return getInt("PropertyId");
	}

}
