package com.cxxy.eta8.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLogReview<M extends BaseLogReview<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setAwardlogId(java.lang.String awardlogId) {
		set("awardlogId", awardlogId);
		return (M)this;
	}
	
	public java.lang.String getAwardlogId() {
		return getStr("awardlogId");
	}

	public M setReviewerName(java.lang.String reviewerName) {
		set("reviewerName", reviewerName);
		return (M)this;
	}
	
	public java.lang.String getReviewerName() {
		return getStr("reviewerName");
	}

	public M setReviewTypeId(java.lang.Integer reviewTypeId) {
		set("reviewTypeId", reviewTypeId);
		return (M)this;
	}
	
	public java.lang.Integer getReviewTypeId() {
		return getInt("reviewTypeId");
	}

}
