package com.cxxy.eta8.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTeacher<M extends BaseTeacher<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTeaNo(java.lang.String teaNo) {
		set("teaNo", teaNo);
		return (M)this;
	}
	
	public java.lang.String getTeaNo() {
		return getStr("teaNo");
	}

	public M setTeaName(java.lang.String teaName) {
		set("teaName", teaName);
		return (M)this;
	}
	
	public java.lang.String getTeaName() {
		return getStr("teaName");
	}

	public M setGenderId(java.lang.Integer genderId) {
		set("genderId", genderId);
		return (M)this;
	}
	
	public java.lang.Integer getGenderId() {
		return getInt("genderId");
	}

	public M setSectorId(java.lang.Integer sectorId) {
		set("sectorId", sectorId);
		return (M)this;
	}
	
	public java.lang.Integer getSectorId() {
		return getInt("sectorId");
	}

	public M setCollegeId(java.lang.Integer collegeId) {
		set("collegeId", collegeId);
		return (M)this;
	}
	
	public java.lang.Integer getCollegeId() {
		return getInt("collegeId");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

}
