package com.cxxy.eta8.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSubjectHorizon<M extends BaseSubjectHorizon<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSubjectId(java.lang.Integer SubjectId) {
		set("SubjectId", SubjectId);
		return (M)this;
	}
	
	public java.lang.Integer getSubjectId() {
		return getInt("SubjectId");
	}

	public M setIntroduction(java.lang.String Introduction) {
		set("Introduction", Introduction);
		return (M)this;
	}
	
	public java.lang.String getIntroduction() {
		return getStr("Introduction");
	}

	public M setRelyCenterSubject(java.lang.String RelyCenterSubject) {
		set("RelyCenterSubject", RelyCenterSubject);
		return (M)this;
	}
	
	public java.lang.String getRelyCenterSubject() {
		return getStr("RelyCenterSubject");
	}

	public M setContractName(java.lang.String ContractName) {
		set("ContractName", ContractName);
		return (M)this;
	}
	
	public java.lang.String getContractName() {
		return getStr("ContractName");
	}

	public M setCooperatePrincipal(java.lang.String CooperatePrincipal) {
		set("CooperatePrincipal", CooperatePrincipal);
		return (M)this;
	}
	
	public java.lang.String getCooperatePrincipal() {
		return getStr("CooperatePrincipal");
	}

	public M setContractNum(java.lang.String ContractNum) {
		set("ContractNum", ContractNum);
		return (M)this;
	}
	
	public java.lang.String getContractNum() {
		return getStr("ContractNum");
	}

	public M setFundNum(java.lang.String FundNum) {
		set("FundNum", FundNum);
		return (M)this;
	}
	
	public java.lang.String getFundNum() {
		return getStr("FundNum");
	}

	public M setEntrustPlaceId(java.lang.Integer EntrustPlaceId) {
		set("EntrustPlaceId", EntrustPlaceId);
		return (M)this;
	}
	
	public java.lang.Integer getEntrustPlaceId() {
		return getInt("EntrustPlaceId");
	}

	public M setCooperateId(java.lang.Integer CooperateId) {
		set("CooperateId", CooperateId);
		return (M)this;
	}
	
	public java.lang.Integer getCooperateId() {
		return getInt("CooperateId");
	}

	public M setContractId(java.lang.Integer ContractId) {
		set("ContractId", ContractId);
		return (M)this;
	}
	
	public java.lang.Integer getContractId() {
		return getInt("ContractId");
	}

	public M setContractFund(java.lang.Integer ContractFund) {
		set("ContractFund", ContractFund);
		return (M)this;
	}
	
	public java.lang.Integer getContractFund() {
		return getInt("ContractFund");
	}

	public M setBankName(java.lang.String BankName) {
		set("BankName", BankName);
		return (M)this;
	}
	
	public java.lang.String getBankName() {
		return getStr("BankName");
	}

	public M setBankAccount(java.lang.String BankAccount) {
		set("BankAccount", BankAccount);
		return (M)this;
	}
	
	public java.lang.String getBankAccount() {
		return getStr("BankAccount");
	}

	public M setIsDutyFree(java.lang.Integer isDutyFree) {
		set("isDutyFree", isDutyFree);
		return (M)this;
	}
	
	public java.lang.Integer getIsDutyFree() {
		return getInt("isDutyFree");
	}

	public M setDutyFreeId(java.lang.String DutyFreeId) {
		set("DutyFreeId", DutyFreeId);
		return (M)this;
	}
	
	public java.lang.String getDutyFreeId() {
		return getStr("DutyFreeId");
	}

	public M setIsPromote(java.lang.Integer isPromote) {
		set("isPromote", isPromote);
		return (M)this;
	}
	
	public java.lang.Integer getIsPromote() {
		return getInt("isPromote");
	}

	public M setContractDuty(java.lang.String ContractDuty) {
		set("ContractDuty", ContractDuty);
		return (M)this;
	}
	
	public java.lang.String getContractDuty() {
		return getStr("ContractDuty");
	}

	public M setPayId(java.lang.Integer PayId) {
		set("PayId", PayId);
		return (M)this;
	}
	
	public java.lang.Integer getPayId() {
		return getInt("PayId");
	}

	public M setEconomicId(java.lang.Integer EconomicId) {
		set("EconomicId", EconomicId);
		return (M)this;
	}
	
	public java.lang.Integer getEconomicId() {
		return getInt("EconomicId");
	}

	public M setSocietyId(java.lang.Integer SocietyId) {
		set("SocietyId", SocietyId);
		return (M)this;
	}
	
	public java.lang.Integer getSocietyId() {
		return getInt("SocietyId");
	}

	public M setSourceId(java.lang.Integer SourceId) {
		set("SourceId", SourceId);
		return (M)this;
	}
	
	public java.lang.Integer getSourceId() {
		return getInt("SourceId");
	}

	public M setTechnicalId(java.lang.Integer TechnicalId) {
		set("TechnicalId", TechnicalId);
		return (M)this;
	}
	
	public java.lang.Integer getTechnicalId() {
		return getInt("TechnicalId");
	}

	public M setPropertyId(java.lang.Integer PropertyId) {
		set("PropertyId", PropertyId);
		return (M)this;
	}
	
	public java.lang.Integer getPropertyId() {
		return getInt("PropertyId");
	}

}
