package com.cxxy.eta8.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSCategory<M extends BaseSCategory<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCategoryName(java.lang.String CategoryName) {
		set("CategoryName", CategoryName);
		return (M)this;
	}
	
	public java.lang.String getCategoryName() {
		return getStr("CategoryName");
	}

	public M setTypeId(java.lang.Integer TypeId) {
		set("TypeId", TypeId);
		return (M)this;
	}
	
	public java.lang.Integer getTypeId() {
		return getInt("TypeId");
	}

}
