package com.cxxy.eta8.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCandidate<M extends BaseCandidate<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCandidateType(java.lang.String CandidateType) {
		set("CandidateType", CandidateType);
		return (M)this;
	}
	
	public java.lang.String getCandidateType() {
		return getStr("CandidateType");
	}

}
