package com.cxxy.eta8.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSFirst<M extends BaseSFirst<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTypeName(java.lang.String TypeName) {
		set("TypeName", TypeName);
		return (M)this;
	}
	
	public java.lang.String getTypeName() {
		return getStr("TypeName");
	}

	public M setRankId(java.lang.Integer RankId) {
		set("RankId", RankId);
		return (M)this;
	}
	
	public java.lang.Integer getRankId() {
		return getInt("RankId");
	}

}
