package com.cxxy.eta8.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserSubject<M extends BaseUserSubject<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSubjectNum(java.lang.String subjectNum) {
		set("subjectNum", subjectNum);
		return (M)this;
	}
	
	public java.lang.String getSubjectNum() {
		return getStr("subjectNum");
	}

	public M setSubjectName(java.lang.String subjectName) {
		set("subjectName", subjectName);
		return (M)this;
	}
	
	public java.lang.String getSubjectName() {
		return getStr("subjectName");
	}

	public M setSubjectTime(java.util.Date subjectTime) {
		set("subjectTime", subjectTime);
		return (M)this;
	}
	
	public java.util.Date getSubjectTime() {
		return get("subjectTime");
	}

	public M setStartTime(java.util.Date startTime) {
		set("startTime", startTime);
		return (M)this;
	}
	
	public java.util.Date getStartTime() {
		return get("startTime");
	}

	public M setFinishTime(java.util.Date FinishTime) {
		set("FinishTime", FinishTime);
		return (M)this;
	}
	
	public java.util.Date getFinishTime() {
		return get("FinishTime");
	}

	public M setCreateAt(java.util.Date createAt) {
		set("createAt", createAt);
		return (M)this;
	}
	
	public java.util.Date getCreateAt() {
		return get("createAt");
	}

	public M setReviewAt(java.util.Date reviewAt) {
		set("reviewAt", reviewAt);
		return (M)this;
	}
	
	public java.util.Date getReviewAt() {
		return get("reviewAt");
	}

	public M setImagePath(java.lang.String imagePath) {
		set("imagePath", imagePath);
		return (M)this;
	}
	
	public java.lang.String getImagePath() {
		return getStr("imagePath");
	}

	public M setRankId(java.lang.Integer rankId) {
		set("rankId", rankId);
		return (M)this;
	}
	
	public java.lang.Integer getRankId() {
		return getInt("rankId");
	}

	public M setLevelId(java.lang.Integer levelId) {
		set("levelId", levelId);
		return (M)this;
	}
	
	public java.lang.Integer getLevelId() {
		return getInt("levelId");
	}

	public M setReviewId(java.lang.Integer reviewId) {
		set("reviewId", reviewId);
		return (M)this;
	}
	
	public java.lang.Integer getReviewId() {
		return getInt("reviewId");
	}

	public M setSubjectPlace(java.lang.String subjectPlace) {
		set("subjectPlace", subjectPlace);
		return (M)this;
	}
	
	public java.lang.String getSubjectPlace() {
		return getStr("subjectPlace");
	}

	public M setSubjectFund(java.lang.Integer subjectFund) {
		set("subjectFund", subjectFund);
		return (M)this;
	}
	
	public java.lang.Integer getSubjectFund() {
		return getInt("subjectFund");
	}

}
