package com.cxxy.eta8.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBCity<M extends BaseBCity<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCity(java.lang.String City) {
		set("City", City);
		return (M)this;
	}
	
	public java.lang.String getCity() {
		return getStr("City");
	}

	public M setProvinceId(java.lang.Integer ProvinceId) {
		set("ProvinceId", ProvinceId);
		return (M)this;
	}
	
	public java.lang.Integer getProvinceId() {
		return getInt("ProvinceId");
	}

}
