package com.cxxy.eta8.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserAward<M extends BaseUserAward<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setAwardTime(java.util.Date awardTime) {
		set("awardTime", awardTime);
		return (M)this;
	}
	
	public java.util.Date getAwardTime() {
		return get("awardTime");
	}

	public M setAwardPlace(java.lang.String awardPlace) {
		set("awardPlace", awardPlace);
		return (M)this;
	}
	
	public java.lang.String getAwardPlace() {
		return getStr("awardPlace");
	}

	public M setCreateAt(java.util.Date createAt) {
		set("createAt", createAt);
		return (M)this;
	}
	
	public java.util.Date getCreateAt() {
		return get("createAt");
	}

	public M setReviewAt(java.util.Date reviewAt) {
		set("reviewAt", reviewAt);
		return (M)this;
	}
	
	public java.util.Date getReviewAt() {
		return get("reviewAt");
	}

	public M setImagePath(java.lang.String imagePath) {
		set("imagePath", imagePath);
		return (M)this;
	}
	
	public java.lang.String getImagePath() {
		return getStr("imagePath");
	}

	public M setUserId(java.lang.Integer userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

	public M setAwardId(java.lang.Integer awardId) {
		set("awardId", awardId);
		return (M)this;
	}
	
	public java.lang.Integer getAwardId() {
		return getInt("awardId");
	}

	public M setRankId(java.lang.Integer rankId) {
		set("rankId", rankId);
		return (M)this;
	}
	
	public java.lang.Integer getRankId() {
		return getInt("rankId");
	}

	public M setReviewId(java.lang.Integer reviewId) {
		set("reviewId", reviewId);
		return (M)this;
	}
	
	public java.lang.Integer getReviewId() {
		return getInt("reviewId");
	}

}
