package com.cxxy.eta8.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("s_belong", "id", SBelong.class);
		arp.addMapping("s_contract", "id", SContract.class);
		arp.addMapping("s_cooperate", "id", SCooperate.class);
		arp.addMapping("s_economic", "id", SEconomic.class);
		arp.addMapping("s_entrust", "id", SEntrust.class);
		arp.addMapping("s_first", "id", SFirst.class);
		arp.addMapping("s_property", "id", SProperty.class);
		arp.addMapping("s_rank", "id", SRank.class);
		arp.addMapping("s_research", "id", SResearch.class);
		arp.addMapping("s_second", "id", SSecond.class);
		arp.addMapping("s_source", "id", SSource.class);
		arp.addMapping("s_technical", "id", STechnical.class);
		arp.addMapping("s_topic", "id", STopic.class);
		arp.addMapping("s_type", "id", SType.class);
		arp.addMapping("sys_url", "id", SysUrl.class);
		arp.addMapping("sys_url_role", "id", SysUrlRole.class);
		arp.addMapping("t_assistant_link_student", "id", AssistantLinkStudent.class);
		arp.addMapping("t_award", "id", Award.class);
		arp.addMapping("t_award_type", "id", AwardType.class);
		arp.addMapping("t_candidate", "id", Candidate.class);
		arp.addMapping("t_class", "id", Class.class);
		arp.addMapping("t_gender", "id", Gender.class);
		arp.addMapping("t_grade", "id", Grade.class);
		arp.addMapping("t_inform", "id", Inform.class);
		arp.addMapping("t_instructor_link_student", "id", InstructorLinkStudent.class);
		arp.addMapping("t_log_review", "id", LogReview.class);
		arp.addMapping("t_log_type", "id", LogType.class);
		arp.addMapping("t_major", "id", Major.class);
		arp.addMapping("t_notice", "id", Notice.class);
		arp.addMapping("t_paper_link_teacher", "id", PaperLinkTeacher.class);
		arp.addMapping("t_paper_rank", "id", PaperRank.class);
		arp.addMapping("t_picture", "id", Picture.class);
		arp.addMapping("t_rank", "id", Rank.class);
		arp.addMapping("t_review", "id", Review.class);
		arp.addMapping("t_role", "id", Role.class);
		arp.addMapping("t_student", "id", Student.class);
		arp.addMapping("t_subject_horizon", "id", SubjectHorizon.class);
		arp.addMapping("t_subject_link_teacher", "id", SubjectLinkTeacher.class);
		arp.addMapping("t_subject_rank", "id", SubjectRank.class);
		arp.addMapping("t_subject_school", "id", SubjectSchool.class);
		arp.addMapping("t_subject_sponsored", "id", SubjectSponsored.class);
		arp.addMapping("t_teacher", "id", Teacher.class);
		arp.addMapping("t_type", "id", Type.class);
		arp.addMapping("t_user", "id", User.class);
		arp.addMapping("t_user_award", "id", UserAward.class);
		arp.addMapping("t_user_paper", "id", UserPaper.class);
		arp.addMapping("t_user_role", "id", UserRole.class);
		arp.addMapping("t_user_subject", "id", UserSubject.class);
	}
}

