package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseAssistantLinkStudent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AssistantLinkStudent extends BaseAssistantLinkStudent<AssistantLinkStudent> {
	public static final AssistantLinkStudent dao = new AssistantLinkStudent().dao();
}
