package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseAward;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Award extends BaseAward<Award> {
	public static final Award dao = new Award().dao();
}
