package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseAwardType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AwardType extends BaseAwardType<AwardType> {
	public static final AwardType dao = new AwardType().dao();
}
