package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseBCity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BCity extends BaseBCity<BCity> {
	public static final BCity dao = new BCity().dao();
}
