package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseBCounty;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BCounty extends BaseBCounty<BCounty> {
	public static final BCounty dao = new BCounty().dao();
}
