package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseBCountry;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BCountry extends BaseBCountry<BCountry> {
	public static final BCountry dao = new BCountry().dao();
}
