package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseBelong;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Belong extends BaseBelong<Belong> {
	public static final Belong dao = new Belong().dao();
}
