package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseBProvince;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BProvince extends BaseBProvince<BProvince> {
	public static final BProvince dao = new BProvince().dao();
}
