package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseBType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BType extends BaseBType<BType> {
	public static final BType dao = new BType().dao();
}
