package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseCandidate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Candidate extends BaseCandidate<Candidate> {
	public static final Candidate dao = new Candidate().dao();
}
