package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseClass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Class extends BaseClass<Class> {
	public static final Class dao = new Class().dao();
}
