package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseCollege;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class College extends BaseCollege<College> {
	public static final College dao = new College().dao();
}
