package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseGender;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Gender extends BaseGender<Gender> {
	public static final Gender dao = new Gender().dao();
}
