package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseHorCountry;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HorCountry extends BaseHorCountry<HorCountry> {
	public static final HorCountry dao = new HorCountry().dao();
}
