package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseHorCounty;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HorCounty extends BaseHorCounty<HorCounty> {
	public static final HorCounty dao = new HorCounty().dao();
}
