package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseHorCity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HorCity extends BaseHorCity<HorCity> {
	public static final HorCity dao = new HorCity().dao();
}
