package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseHorizonCounty;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HorizonCounty extends BaseHorizonCounty<HorizonCounty> {
	public static final HorizonCounty dao = new HorizonCounty().dao();
}
