package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseHorizonCity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HorizonCity extends BaseHorizonCity<HorizonCity> {
	public static final HorizonCity dao = new HorizonCity().dao();
}
