package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseHorizonType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HorizonType extends BaseHorizonType<HorizonType> {
	public static final HorizonType dao = new HorizonType().dao();
}
