package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseHorizonProvince;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HorizonProvince extends BaseHorizonProvince<HorizonProvince> {
	public static final HorizonProvince dao = new HorizonProvince().dao();
}
