package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseHorizonCountry;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HorizonCountry extends BaseHorizonCountry<HorizonCountry> {
	public static final HorizonCountry dao = new HorizonCountry().dao();
}
