package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseHorProvince;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HorProvince extends BaseHorProvince<HorProvince> {
	public static final HorProvince dao = new HorProvince().dao();
}
