package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseHorType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HorType extends BaseHorType<HorType> {
	public static final HorType dao = new HorType().dao();
}
