package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseInform;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Inform extends BaseInform<Inform> {
	public static final Inform dao = new Inform().dao();
}
