package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseInstructorLinkStudent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InstructorLinkStudent extends BaseInstructorLinkStudent<InstructorLinkStudent> {
	public static final InstructorLinkStudent dao = new InstructorLinkStudent().dao();
}
