package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseLevel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Level extends BaseLevel<Level> {
	public static final Level dao = new Level().dao();
}
