package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseLogReview;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogReview extends BaseLogReview<LogReview> {
	public static final LogReview dao = new LogReview().dao();
}
