package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseMajor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Major extends BaseMajor<Major> {
	public static final Major dao = new Major().dao();
}
