package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BasePaperRank;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PaperRank extends BasePaperRank<PaperRank> {
	public static final PaperRank dao = new PaperRank().dao();
}
