package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BasePaperLinkTeacher;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PaperLinkTeacher extends BasePaperLinkTeacher<PaperLinkTeacher> {
	public static final PaperLinkTeacher dao = new PaperLinkTeacher().dao();
}
