package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BasePicture;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Picture extends BasePicture<Picture> {
	public static final Picture dao = new Picture().dao();
}
