package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseRank;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Rank extends BaseRank<Rank> {
	public static final Rank dao = new Rank().dao();
}
