package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Record extends BaseRecord<Record> {
	public static final Record dao = new Record().dao();
}
