package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseResearch;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Research extends BaseResearch<Research> {
	public static final Research dao = new Research().dao();
}
