package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseReview;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Review extends BaseReview<Review> {
	public static final Review dao = new Review().dao();
}
