package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSBelong;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SBelong extends BaseSBelong<SBelong> {
	public static final SBelong dao = new SBelong().dao();
}
