package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SCategory extends BaseSCategory<SCategory> {
	public static final SCategory dao = new SCategory().dao();
}
