package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSCategoryCopy1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SCategoryCopy1 extends BaseSCategoryCopy1<SCategoryCopy1> {
	public static final SCategoryCopy1 dao = new SCategoryCopy1().dao();
}
