package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSCategorySecond;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SCategorySecond extends BaseSCategorySecond<SCategorySecond> {
	public static final SCategorySecond dao = new SCategorySecond().dao();
}
