package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSContract;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SContract extends BaseSContract<SContract> {
	public static final SContract dao = new SContract().dao();
}
