package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSContractThird;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SContractThird extends BaseSContractThird<SContractThird> {
	public static final SContractThird dao = new SContractThird().dao();
}
