package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSContractSecond;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SContractSecond extends BaseSContractSecond<SContractSecond> {
	public static final SContractSecond dao = new SContractSecond().dao();
}
