package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSContractSecondThird;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SContractSecondThird extends BaseSContractSecondThird<SContractSecondThird> {
	public static final SContractSecondThird dao = new SContractSecondThird().dao();
}
