package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSCooperate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SCooperate extends BaseSCooperate<SCooperate> {
	public static final SCooperate dao = new SCooperate().dao();
}
