package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSEcoSecond;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SEcoSecond extends BaseSEcoSecond<SEcoSecond> {
	public static final SEcoSecond dao = new SEcoSecond().dao();
}
