package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSEcoFirst;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SEcoFirst extends BaseSEcoFirst<SEcoFirst> {
	public static final SEcoFirst dao = new SEcoFirst().dao();
}
