package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSEconomic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SEconomic extends BaseSEconomic<SEconomic> {
	public static final SEconomic dao = new SEconomic().dao();
}
