package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSector;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Sector extends BaseSector<Sector> {
	public static final Sector dao = new Sector().dao();
}
