package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSEntrust;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SEntrust extends BaseSEntrust<SEntrust> {
	public static final SEntrust dao = new SEntrust().dao();
}
