package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSFirst;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SFirst extends BaseSFirst<SFirst> {
	public static final SFirst dao = new SFirst().dao();
}
