package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSProperty;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SProperty extends BaseSProperty<SProperty> {
	public static final SProperty dao = new SProperty().dao();
}
