package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSRank;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SRank extends BaseSRank<SRank> {
	public static final SRank dao = new SRank().dao();
}
