package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSResearchArea;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SResearchArea extends BaseSResearchArea<SResearchArea> {
	public static final SResearchArea dao = new SResearchArea().dao();
}
