package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSResearch;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SResearch extends BaseSResearch<SResearch> {
	public static final SResearch dao = new SResearch().dao();
}
