package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSResearchType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SResearchType extends BaseSResearchType<SResearchType> {
	public static final SResearchType dao = new SResearchType().dao();
}
