package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSSchool;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SSchool extends BaseSSchool<SSchool> {
	public static final SSchool dao = new SSchool().dao();
}
