package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSSecond;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SSecond extends BaseSSecond<SSecond> {
	public static final SSecond dao = new SSecond().dao();
}
