package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSSociety;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SSociety extends BaseSSociety<SSociety> {
	public static final SSociety dao = new SSociety().dao();
}
