package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSSource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SSource extends BaseSSource<SSource> {
	public static final SSource dao = new SSource().dao();
}
