package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSSubjectSecond;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SSubjectSecond extends BaseSSubjectSecond<SSubjectSecond> {
	public static final SSubjectSecond dao = new SSubjectSecond().dao();
}
