package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSSubjectFirst;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SSubjectFirst extends BaseSSubjectFirst<SSubjectFirst> {
	public static final SSubjectFirst dao = new SSubjectFirst().dao();
}
