package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSSubjectThird;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SSubjectThird extends BaseSSubjectThird<SSubjectThird> {
	public static final SSubjectThird dao = new SSubjectThird().dao();
}
