package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSTechnical;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class STechnical extends BaseSTechnical<STechnical> {
	public static final STechnical dao = new STechnical().dao();
}
