package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSTopic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class STopic extends BaseSTopic<STopic> {
	public static final STopic dao = new STopic().dao();
}
