package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SType extends BaseSType<SType> {
	public static final SType dao = new SType().dao();
}
