package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSubjectRank;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SubjectRank extends BaseSubjectRank<SubjectRank> {
	public static final SubjectRank dao = new SubjectRank().dao();
}
