package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSubjectSchool;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SubjectSchool extends BaseSubjectSchool<SubjectSchool> {
	public static final SubjectSchool dao = new SubjectSchool().dao();
}
