package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSubjectLinkPaper;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SubjectLinkPaper extends BaseSubjectLinkPaper<SubjectLinkPaper> {
	public static final SubjectLinkPaper dao = new SubjectLinkPaper().dao();
}
