package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSubjectHorizon;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SubjectHorizon extends BaseSubjectHorizon<SubjectHorizon> {
	public static final SubjectHorizon dao = new SubjectHorizon().dao();
}
