package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSubjectSponsored;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SubjectSponsored extends BaseSubjectSponsored<SubjectSponsored> {
	public static final SubjectSponsored dao = new SubjectSponsored().dao();
}
