package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSubjectLinkTeacher;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SubjectLinkTeacher extends BaseSubjectLinkTeacher<SubjectLinkTeacher> {
	public static final SubjectLinkTeacher dao = new SubjectLinkTeacher().dao();
}
