package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSysUrlRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUrlRole extends BaseSysUrlRole<SysUrlRole> {
	public static final SysUrlRole dao = new SysUrlRole().dao();
}
