package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseSysUrl;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUrl extends BaseSysUrl<SysUrl> {
	public static final SysUrl dao = new SysUrl().dao();
}
