package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseTeacher;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Teacher extends BaseTeacher<Teacher> {
	public static final Teacher dao = new Teacher().dao();
}
