package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseUserPaper;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserPaper extends BaseUserPaper<UserPaper> {
	public static final UserPaper dao = new UserPaper().dao();
}
