package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseUserAward;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserAward extends BaseUserAward<UserAward> {
	public static final UserAward dao = new UserAward().dao();
}
