package com.cxxy.eta8.model;

import com.cxxy.eta8.model.base.BaseUserSubject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserSubject extends BaseUserSubject<UserSubject> {
	public static final UserSubject dao = new UserSubject().dao();
}
